### ISSUE TITLE
DAT failure: Url encoding issue

### ISSUE THREAD

**Issue by samansmink** [delta-io/delta-kernel-rs#262]
For the DAT tests `multi_partitioned` and `multi_partitioned_2` In the [duckdb delta extension](https://github.com/duckdb/duckdb_delta) I'm seeing doubly url encoded paths.

To reproduce, run DuckDB v1.0.0:
```SQL
force install delta from core_nightly
from delta_scan('delta_kernel_rs/acceptance/tests/dat/out/reader_tests/generated/multi_partitioned/delta');
```

results in:
```
IO Error: Cannot open file "../../../acceptance/tests/dat/out/reader_tests/generated/multi_partitioned/delta/letter=%252F%252520%2525f/date=1970-01-01/data=hello/part-00000-a29a3f63-5a26-4127-aeff-e6d27c077917.c000.snappy.parquet":
```
Note that the letter column contains the partition value `%252F%252520%2525f` which should be `%2F%2520%25f`. This means that somewhere the value is urlencoded again where it shouldn't.

These paths are exactly what I get back in the callback passed to the `ffi::visit_scan_data` function, so I'm pretty sure the issue is kernel side?

Weirdly this is fine when I query the tables using `delta-kernel-rs/kernel/examples/read-table-multi-threaded`:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `/Users/sam/Development/delta-kernel-rs/target/debug/read-table-multi-threaded -e sync ../../../acceptance/tests/dat/out/reader_tests/generated/multi_partitioned/delta`
Reading file:///Users/sam/Development/delta-kernel-rs/acceptance/tests/dat/out/reader_tests/generated/multi_partitioned/delta/
+--------+------------+------------+--------+
| letter | date       | data       | number |
+--------+------------+------------+--------+
| b      | 1970-01-01 | f09f9888   | 7      |
| /%20%f | 1970-01-01 | 68656c6c6f | 6      |
+--------+------------+------------+--------+

```

**Comment by nicklan** [comment]
Yeah, so the issue is that kernel deals all in urls. So the if your code isn't expecting a URL, then you need to decode it. `
%2F%2520%25f` is the _actual_ path name, while `%252F%252520%2525f` is the url encoded version. It's not been encoded "again", just once, it's just that the actual path looks encoded in this case.

So the file is at:
- Url version: `file:///path/to/acceptance/tests/dat/out/reader_tests/generated/multi_partitioned/delta/letter=%252F%252520%2525f/date=1970-01-01/data=hello/part-00000-0b6e3269-8890-4556-9dca-d4032ea9a952.c000.snappy.parquet`
- fs path version: `/path/to/acceptance/tests/dat/out/reader_tests/generated/multi_partitioned/delta/letter=%2F%2520%25f/date=1970-01-01/data=hello/part-00000-0b6e3269-8890-4556-9dca-d4032ea9a952.c000.snappy.parquet`

What makes this tricky is that we pass these as strings, because we can't pass a "url class" over ffi. If you have url decoding in duckdb, the right thing to do would be to create the url and then decode it. Also, from the error it looks like you're using the path that the user types in as the "table root". Once #203 finally merges I'd recommend using [`snapshot_table_root`](https://github.com/delta-incubator/delta-kernel-rs/pull/203/files#diff-9f8aacd1a2531f6bbaed2e3290b7c5f18fbfb82147bcdafabb807cab66383715R666), which will give you the actual expended root url of the table. Then you can just parse the whole thing as a url.

If you want to use a file-path, I _think_ it should just work to url-decode the value that comes in as the `path` to `visit_callback`.

**Comment by samansmink** [comment]
ah yea that makes sense, okay I will just fix this DuckDB side by url decoding
